name: Update Translation Progress
description: Displays the translation progress for each language in the repository readme.
author: Roules

inputs:
    gh-token:
        description: 'The GitHub token for authentication.'
        required: true
    
    readme-path:
        description: 'The path to the README file to update.'
        required: false
        default: 'README.md'
    
    locales-dir:
        description: 'The directory where locale files are stored.'
        required: false
        default: 'locales'

    reference-locale:
        description: 'The reference locale to compare against (e.g., "en").'
        required: false
        default: 'en-US'

runs:
    using: node24
    main: dist/index.js

branding:
    color: purple
    icon: globe
