name: Update Translation Progress
description: Displays the translation progress for each language in the repository readme.

inputs:
  who-to-greet: # id of input
    description: Who to greet
    required: true
    default: World

outputs:
  time: # id of output
    description: The time we greeted you

runs:
  using: node23
  main: dist/index.js
